import Head from 'next/head';

export default function Home() {
  return (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <h1>Hello World</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, voluptatem!</p>
            <div>
                <h1>Join Today</h1>
                <p>Sign in with one of the providers</p>
                <div>
                    <button>Sign in with Google</button>
                    <button>Sign in with Facebook</button>
                </div>
            </div>
        </main>
    </>
  )
}
